version: 2

models:
  - name: stg_books
    columns:
      - name: book_id
        tests: [unique, not_null]

  - name: stg_members
    columns:
      - name: member_id
        tests: [unique, not_null]

  - name: stg_loans
    columns:
      - name: loan_id
        tests: [unique, not_null]
      - name: book_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_books')
              field: book_id
      - name: member_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_members')
              field: member_id
